name: Run unit tests

on: push
  branches:
    - 'main'
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run migrations
      working-directory: .
      run: `bazel build //examples/cpp/helloworld:greeter_client`